#{{- if .Values.argoPostSync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: integration-test
  namespace: apps
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    
spec:
  ttlSecondsAfterFinished: 100000
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          #image: badouralix/curl-jq:latest
          imagePullPolicy: Always
          env:
            - name: ARGO_POSTSYNC_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argo-postsync-secret
                  key: token
            - name: ARGO_POSTSYNC_TARGET_ENV
              value: "UAT" # {{ .Values.argoPostSync.targetEnvFile }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              # echo "ARGO_POSTSYNC_TARGET_ENV" : ${ARGO_POSTSYNC_TARGET_ENV} 
              # echo "ARGO_POSTSYNC_GITHUB_TOKEN" : ${ARGO_POSTSYNC_GITHUB_TOKEN}
              # echo "Starting command" && \
              # JSON_PAYLOAD="{\"ref\":\"workflow-automation\",\"inputs\":{\"target_env\":\"$ARGO_POSTSYNC_TARGET_ENV\"}}" && \
              # echo "JSON_PAYLOAD: ${JSON_PAYLOAD}" && \
              # echo "${JSON_PAYLOAD}" > payload.json && \
              # cat payload.json && \
              # curl -L -X POST -H "Accept: application/vnd.github+json" \
              #   -H "Authorization: Bearer ${ARGO_POSTSYNC_GITHUB_TOKEN}" \
              #   -H "X-GitHub-Api-Version: 2022-11-28" \
              #   https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches \
              #   -d $JSON_PAYLOAD && \
              # echo "Done initiating pipeline" && \
              # sleep 10 && \
              # echo "Command execution complete"

              # echo "Starting command" && \
              # echo "GITHUB_TOKEN: ${ARGO_POSTSYNC_GITHUB_TOKEN}" && \
              # echo "TARGET_ENV: ${ARGO_POSTSYNC_TARGET_ENV}" && \
              # JSON_PAYLOAD="{\"ref\":\"workflow-automation\",\"inputs\":{\"target_env\":\"${ARGO_POSTSYNC_TARGET_ENV}\"}}" && \
              # curl -v -L -X POST -H "Accept: application/vnd.github+json" \
              #   -H "Authorization: Bearer ${ARGO_POSTSYNC_GITHUB_TOKEN}" \
              #   -H "X-GitHub-Api-Version: 2022-11-28" \
              #   https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches \
              #   -d "{\"ref\":\"workflow-automation\"}" && \
              # echo "Done initiating pipeline" && \
              # sleep 10 && \
              # echo "Command execution complete"


              ### NEW TEST
              echo "Starting command" && \
              echo "GITHUB_TOKEN: ${ARGO_POSTSYNC_GITHUB_TOKEN}" && \
              echo "TARGET_ENV: ${ARGO_POSTSYNC_TARGET_ENV}" && \
              JSON_PAYLOAD="{\"ref\":\"workflow-automation\",\"inputs\":{\"target-env\":\"${ARGO_POSTSYNC_TARGET_ENV}\"}}" && \
              # Remove any trailing newlines from JSON_PAYLOAD
              JSON_PAYLOAD=$(echo $JSON_PAYLOAD | tr -d '\n') && \
              echo "${JSON_PAYLOAD}" > payload.json && \
              echo "Contents of payload.json:" && \
              cat payload.json && \
              echo "Hexdump of payload.json:" && \
              hexdump -C payload.json && \
              curl -L -X POST -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${ARGO_POSTSYNC_GITHUB_TOKEN}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches \
                -d "@payload.json" && \
              echo "Done initiating pipeline" && \
              sleep 10 && \
              echo "Command execution complete"


              # # POSTMAN OUTPUT
              # echo "Starting command" && \
              # echo "GITHUB_TOKEN: ${ARGO_POSTSYNC_GITHUB_TOKEN}" && \
              # echo "TARGET_ENV: ${ARGO_POSTSYNC_TARGET_ENV}" && \
              # JSON_PAYLOAD="{\"ref\":\"workflow-automation\",\"inputs\":{\"target_env\":\"${ARGO_POSTSYNC_TARGET_ENV}\"}}" && \
              # # Remove any trailing newlines from JSON_PAYLOAD
              # JSON_PAYLOAD=$(echo $JSON_PAYLOAD | tr -d '\n') && \
              # echo "JSON_PAYLOAD: ${JSON_PAYLOAD}" > payload.json && \
              # echo "Creating Postman request JSON..." && \
              # POSTMAN_REQUEST_JSON=$(cat <<EOF
              # {
              #   "method": "POST",
              #   "header": [
              #     {
              #       "key": "Accept",
              #       "value": "application/vnd.github+json"
              #     },
              #     {
              #       "key": "Authorization",
              #       "value": "Bearer ${ARGO_POSTSYNC_GITHUB_TOKEN}"
              #     },
              #     {
              #       "key": "X-GitHub-Api-Version",
              #       "value": "2022-11-28"
              #     }
              #   ],
              #   "url": {
              #     "raw": "https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches",
              #     "protocol": "https",
              #     "host": [
              #       "api",
              #       "github",
              #       "com"
              #     ],
              #     "path": [
              #       "repos",
              #       "Irembo",
              #       "irembopay-api-integration-tests",
              #       "actions",
              #       "workflows",
              #       "release.yaml",
              #       "dispatches"
              #     ]
              #   },
              #   "body": {
              #     "mode": "raw",
              #     "raw": ${JSON_PAYLOAD}
              #   }
              # }
              # EOF

              # ) && \
              # echo "${POSTMAN_REQUEST_JSON}" > postman_request.json && \
              # echo "Contents of postman_request.json:" && \
              # cat postman_request.json && \
              # curl -v -L -X POST -H "Accept: application/vnd.github+json" \
              #   -H "Authorization: Bearer ${ARGO_POSTSYNC_GITHUB_TOKEN}" \
              #   -H "X-GitHub-Api-Version: 2022-11-28" \
              #   https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches \
              #   -d @payload.json && \
              # echo "Done initiating pipeline" && \
              # sleep 10 && \
              # echo "Command execution complete"
              
      restartPolicy: Never
  backoffLimit: 1
#{{- end }}
