{{- if .Values.argoPostSync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: integration-test
  namespace: apps
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    
spec:
  ttlSecondsAfterFinished: 100000
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          imagePullPolicy: Always
          env:
            - name:  ARGO_POSTSYNC_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argo-postsync-secret
                  key: token
            - name: ARGO_POSTSYNC_TARGET_ENV
              value: {{ .Values.argoPostSync.targetEnvFile }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "ARGO_POSTSYNC_TARGET_ENV" : ${ARGO_POSTSYNC_TARGET_ENV} 
              echo "ARGO_POSTSYNC_GITHUB_TOKEN" : ${ARGO_POSTSYNC_GITHUB_TOKEN}

              # Check if Environment Variables are set
              if [[ -z "$ARGO_POSTSYNC_TARGET_ENV}" || -z "$ARGO_POSTSYNC_GITHUB_TOKEN" ]]; then
                echo "Environment variables are not set. Please make sure ARGO_POSTSYNC_TARGET_ENV and ARGO_POSTSYNC_GITHUB_TOKEN are defined."
                exit 1
              fi

              echo "starting command" && \
              # curl -L -X POST -H "Accept: application/vnd.github+json" \
              #   -H "Authorization: Bearer ${ARGO_POSTSYNC_GITHUB_TOKEN}" \
              #   -H "X-GitHub-Api-Version: 2022-11-28" \
              #   https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches \
              #   -d '{"ref":"workflow-automation","inputs": {"target_env":"${ARGO_POSTSYNC_TARGET_ENV}"}}' && \

              curl -L -X POST -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${ARGO_POSTSYNC_GITHUB_TOKEN}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches \
                -d @- << EOF && \
                {
                  "ref": "workflow-automation",
                  "inputs":{
                    "target_env": "${ARGO_POSTSYNC_TARGET_ENV}"
                  }
                }
                EOF 
              echo "Done initiating pipeline"

      restartPolicy: Never
  backoffLimit: 1

  {{- end }}
