apiVersion: batch/v1
kind: Job
metadata:
  name: integration-test
  namespace: apps
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    
spec:
  ttlSecondsAfterFinished: 100000
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          imagePullPolicy: Always
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "starting command" && \
              curl -L -X POST -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/s-nzayisenga/hello-java-app/actions/workflows/dispatch.yaml/dispatches \
                -d '{"ref":"main","inputs": {"target_env":"DEV"}}' && \
              echo "Done initiating pipeline"

      restartPolicy: Never
  backoffLimit: 1
