#{{- if .Values.argoPostSync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: integration-test
  namespace: apps
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    
spec:
  ttlSecondsAfterFinished: 100000
  template:
    spec:
      containers:
        - name: curl
          #image: curlimages/curl
          image: badouralix/curl-jq:latest
          imagePullPolicy: Always
          env:
            - name: ARGO_POSTSYNC_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argo-postsync-secret
                  key: token
            - name: ARGO_POSTSYNC_TARGET_ENV
              value: "UAT.json"
              ## {{ .Values.argoPostSync.targetEnvFile }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "starting command" && \
              echo "GITHUB_TOKEN: $ARGO_POSTSYNC_GITHUB_TOKEN" && \
              echo "TARGET_ENV: $ARGO_POSTSYNC_TARGET_ENV" && \
              curl -v -L -X POST -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $ARGO_POSTSYNC_GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -d "{\"ref\":\"workflow-automation\"}" \
                https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches 
              echo "Done initiating pipeline" && \
              sleep 5
              echo "Done executing pipeline"
              
      restartPolicy: Never
  backoffLimit: 1
#{{- end }}
