{{- if .Values.argoPostSync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: integration-test
  namespace: apps
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    
spec:
  ttlSecondsAfterFinished: 100000
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          imagePullPolicy: Always
          env:
            - name:  ARGO_POSTSYNC_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argo-postsync-secret
                  key: token
            - name: ARGO_POSTSYNC_TARGET_ENV
              value: {{ .Values.argoPostSync.targetEnvFile | quote }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "ARGO_POSTSYNC_TARGET_ENV" : ${ARGO_POSTSYNC_TARGET_ENV} 
              echo "ARGO_POSTSYNC_GITHUB_TOKEN" : ${ARGO_POSTSYNC_GITHUB_TOKEN}

              # Check if Environment Variables are set
              if [[ -z "$ARGO_POSTSYNC_TARGET_ENV}" || -z "$ARGO_POSTSYNC_GITHUB_TOKEN" ]]; then
                echo "Environment variables are not set. Please make sure ARGO_POSTSYNC_TARGET_ENV and ARGO_POSTSYNC_GITHUB_TOKEN are defined."
                exit 1
              fi

              echo "starting command"
              echo "Done initiating pipeline"
      restartPolicy: Never
  backoffLimit: 1

  {{- end }}
