#{{- if .Values.argoPostSync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: integration-test
  namespace: apps
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    
spec:
  ttlSecondsAfterFinished: 100000
  template:
    spec:
      containers:
        - name: curl
          #image: curlimages/curl
          image: badouralix/curl-jq:latest
          imagePullPolicy: Always
          env:
            - name:  ARGO_POSTSYNC_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argo-postsync-secret
                  key: token
            - name: ARGO_POSTSYNC_TARGET_ENV
              value: DEV.json # {{ .Values.argoPostSync.targetEnvFile }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "ARGO_POSTSYNC_TARGET_ENV" : ${ARGO_POSTSYNC_TARGET_ENV} 
              echo "ARGO_POSTSYNC_GITHUB_TOKEN" : ${ARGO_POSTSYNC_GITHUB_TOKEN}

              # WORKS LOCALLY, TRIGGER PIPELINE
              sleep 10 && \
              echo "starting command" && \
              payload=$(jq -n --arg ref "workflow-automation" --arg target_env "$ARGO_POSTSYNC_TARGET_ENV" '{ref: $ref, inputs: {target_env: $target_env}}') && \
              curl -L -X POST -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${ARGO_POSTSYNC_GITHUB_TOKEN}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches \
                -d "$payload" && \
              echo "Done initiating pipeline"
              sleep 10

              # WORKS LOCALLY, & TRIGGER PIPELINE
              echo "Starting command Again" && \
              echo "GITHUB_TOKEN: ${ARGO_POSTSYNC_GITHUB_TOKEN}" && \
              echo "TARGET_ENV: ${ARGO_POSTSYNC_TARGET_ENV}" && \
              JSON_PAYLOAD="{\"ref\":\"workflow-automation\",\"inputs\":{\"target_env\":\"${ARGO_POSTSYNC_TARGET_ENV}\"}}" && \
              echo "JSON_PAYLOAD: ${JSON_PAYLOAD}" && \
              curl -v -L POST -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${ARGO_POSTSYNC_GITHUB_TOKEN}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches \
                -d "${JSON_PAYLOAD}" && \
              echo "Done initiating pipeline" && \
              sleep 10 && \
              echo "All Commands execution complete"
              
      restartPolicy: Never
  backoffLimit: 1
#{{- end }}
