apiVersion: v1
kind: Namespace
metadata:
  name: second-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: second-app
spec:
  #replicas: "{{ .Values.replicaCount }}"
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: ghcr.io/s-nzayisenga/hello-java-app:v1.0.4
          #image: "{{ .Values.deploymentconfigs.repository }}:{{ .Values.deploymentconfigs.image.tag }}"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: second-app
spec:
  selector:
    app: java-app
  ports:
    - name: http 
      protocol: TCP
      port: 80
      targetPort: 8080
      #nodePort: 30012
  #type: LoadBalancer
  type: ClusterIP
