name: Dispach Release Workflow

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Target environment'
        required: true
        default: 'DEV'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use the target environment
        run: echo "The target environment is ${{ github.event.inputs.target_env }}"

